language: php
php:
  - '7.1'

install:
  - composer install
  - npm install

  # Install for ESLint tests
  - cd packages/eslint-config-chancedigital-wp
  - npm install

  # Reset
  - cd ../..

script:
  - vendor/bin/phpunit
  - node packages/eslint-config-chancedigital-wp/fixtures/test-lint-config
