language: php
php:
  - '7.1'

install:
  - composer install
  - npm install

  # Install for ESLint tests
  - cd packages/chancedigital-eslint-config-wp
  - npm install

  # Reset
  - cd ../..

script:
  - vendor/bin/phpunit
  - node packages/chancedigital-eslint-config-wp/fixtures/test-lint-config
